import { defineConfig } from "tsdown"

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY TSDOWN
if you want to view the source, please visit the github repository of this plugin
*/`

export default defineConfig({
  entry: "src/main.tsx", // Use string, not object, for single output
  outDir: ".",
  outExtensions() {
    return { js: ".js" }
  },
  format: "cjs",
  target: "es2018",
  sourcemap: process.env.NODE_ENV === "production" ? false : "inline",
  minify: process.env.NODE_ENV === "production",
  shims: true,
  banner: {
    js: banner,
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  noExternal: [
    "react",
    "react-dom",
    "react/jsx-runtime",
    "react-dom/client",
    "@tanstack/react-query",
    "@tanstack/react-query-devtools",
  ],
  treeshake: true,
  clean: false,
  dts: false,
  outputOptions: {
    inlineDynamicImports: true,
  },
})
