import svelte from "rollup-plugin-svelte"
import sveltePreprocess from "svelte-preprocess"
import { defineConfig } from "tsdown"

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY TSDOWN
if you want to view the source, please visit the github repository of this plugin
*/`

export default defineConfig({
  entry: "src/main.ts",
  outDir: ".",
  outExtensions() {
    return { js: ".js" }
  },
  format: "cjs",
  target: "es2018",
  sourcemap: process.env.NODE_ENV === "production" ? false : "inline",
  minify: process.env.NODE_ENV === "production",
  shims: true,
  banner: {
    js: banner,
  },
  plugins: [
    svelte({
      preprocess: sveltePreprocess(),
      compilerOptions: {
        css: "injected",
      },
    }),
  ],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  noExternal: ["@stores/*", "@ui/*", "@hooks/*", "@api/*"],
  treeshake: true,
  clean: false,
  dts: false,
  outputOptions: {
    inlineDynamicImports: true,
  },
})
