import { defineConfig } from "tsup"

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY TSUP
if you want to view the source, please visit the github repository of this plugin
*/`

export default defineConfig({
  entry: {
    main: "src/main.tsx",
  },
  outDir: ".",
  outExtension() {
    return { js: ".js" }
  },
  format: ["cjs"],
  target: "es2018",
  sourcemap: process.env.NODE_ENV === "production" ? false : "inline",
  minify: process.env.NODE_ENV === "production",
  shims: true,
  banner: {
    js: banner,
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  noExternal: [
    "react",
    "react-dom",
    "@tanstack/react-query",
    "@tanstack/react-query-devtools",
  ],
  esbuildOptions(options) {
    options.treeShaking = true
  },
})
